### ISSUE TITLE
[2023 Day 10 Part 2] Should take absolute value?

### ISSUE THREAD

**Issue by tristan-zander** [adriandelgado/advent-of-code#1]
https://github.com/adriandelgado/advent-of-code/blob/be7095acd70c959364843c035dd0c7062b282fe6/src/y2023/d10.rs#L134C5-L134C40

Hey! I'm also doing Advent of Code in Rust and I've been following your answer for Day 10. I have having issues after my initial try so I followed your implementation, and it seems as if there might be a small flaw with this part of the code in particular (at least, in my experimentation).

Based on what I saw on [Wikipedia](https://en.wikipedia.org/wiki/Pick's_theorem#Generalizations), it seems like the return value of the shoelace formula should be signed before being put through Pick's Theorem.

Pick's Theorem evaluates to `i = A - (b / 2) - h + 1` when solving for the number of enclosed points, so I think the code for the return value should actually be the following:
```rust
   (twice_area / 2).abs() - (loop_len / 2) + 1
```
I'm not totally sure if I'm correct here since I barely understand the math. I thought it would be interesting to see whether this was correct or not, because I couldn't get your version to work with the examples, even though it also worked with my normal input.

My solution derived from yours, if you're interested: https://github.com/tristan-zander/advent-of-code-2023/blob/main/src/day_ten.rs#L267-L316

**Comment by adriandelgado** [comment]
You are absolutely right. I updated my solution a couple of hours ago. The Shoelace formula is sensitive to the direction you visit the points. They must be visited in a counter clockwise direction if you want the answer to be positive directly.

**Comment by adriandelgado** [comment]
The solution you saw had some hard coded assumptions. Check out the current one, it works on any input and is 10 times faster than the previous one. It also does not make any allocations and only uses the std library.
